### ISSUE TITLE
Squadratura

### ISSUE THREAD

**Issue by flavioprattico** [GIPAT-Polyshaper/PolyShaper_inkscape#1]
Realizzare una squadratura alla fine di tutta la lavorazione. Vedere se farla di dimensioni precise date dall'utente (es. rettangolo 20x10 cm e disegno centrato) oppure dare la possibilità di definire la dimensione dei margini rispetto al disegno.

**Comment by Tomassino** [comment]
Solving in branch [square-result](/GIPAT-Polyshaper/PolyShaper_inkscape/tree/square-result)

**Comment by Tomassino** [comment]
Fixed #8
