### ISSUE TITLE
toolpath drawing 

### ISSUE THREAD

**Issue by flavioprattico** [GIPAT-Polyshaper/PolyShaper_inkscape#4]

**Comment by Tomassino** [comment]
Solving in branch [toolpath-drawing](/GIPAT-Polyshaper/PolyShaper_inkscape/tree/toolpath-drawing)

**Comment by Tomassino** [comment]
Draw toolpath inside the working area SVG element with a solid red line. Add an advanced configuration option to enable/disable drawing. Also replace the toolpath drawing when the plugin is invoked the second time

**Comment by Tomassino** [comment]
Fixed #16
