### ISSUE TITLE
Working time estimation

### ISSUE THREAD

**Issue by flavioprattico** [GIPAT-Polyshaper/PolyShaper_inkscape#6]
Once the gcode is generated, in the pop-up window that gives the path in which the new gcode is stored, give the estimated time (Feed rate, given as input, devided by the total path in mm)

**Comment by Tomassino** [comment]
Solving in branch [working-time-estimation](/GIPAT-Polyshaper/PolyShaper_inkscape/tree/working-time-estimation)

**Comment by Tomassino** [comment]
Fixed #12
